on: [push]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.10.5', '9.2.1', '9.6.2']
        cabal: ['3.10.1.0']
        os: [ubuntu-latest]
        redis-version: [6, 7]
    services:
      redis:
        image: "redis:${{ matrix.redis-version }}"
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    name: GHC ${{ matrix.ghc }} / Cabal ${{ matrix.cabal }} / Redis ${{ matrix.redis-version}}/ ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal build --enable-tests --enable-benchmarks
      - run: cabal install doctest
      - run: cabal repl --with-ghc=doctest
      - run: cabal test test:hedis-test
      - run: cabal test test:redis7
        if: ${{ matrix.redis-version == 7}}
