on: [push]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.10.5', '9.2.1', '9.6.2']
        cabal: ['3.10.1.0']
        os: [ubuntu-latest]
        redis-version: [6, 7]
    name: GHC ${{ matrix.ghc }} / Cabal ${{ matrix.cabal }} / Redis ${{ matrix.redis-version}}/ ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal build --enable-tests --enable-benchmarks
      - run: cabal install doctest
      - run: cabal repl --with-ghc=doctest
      - name: Start redis
        uses: supercharge/redis-github-action@1.5.0
        with:
         redis-version: ${{ matrix.redis-versionn }}
      - run: cabal test test:hedis-test
      - run: cabal test test:redis7
        if: ${{ matrix.redis-version == 7}}
